framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '%env(SYMFONY_TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    session:
        handler_id: app.session_handler
    csrf_protection: true
    rate_limiter:
        admin_login:
            policy: sliding_window
            limit: 5
            interval: '1 minute'
            storage_service: app.rate_limiter_storage
        admin_setup:
            policy: sliding_window
            limit: 5
            interval: '1 minute'
            storage_service: app.rate_limiter_storage
        admin_setup_mode:
            policy: sliding_window
            limit: 5
            interval: '1 minute'
            storage_service: app.rate_limiter_storage
        post_short:
            policy: sliding_window
            limit: 2
            interval: '10 seconds'
            storage_service: app.rate_limiter_storage
        post_hourly:
            policy: sliding_window
            limit: 30
            interval: '1 hour'
            storage_service: app.rate_limiter_storage
        post:
            policy: compound
            limiters:
                - post_short
                - post_hourly
        post_duplicate:
            policy: sliding_window
            limit: 1
            interval: '3 minutes'
            storage_service: app.rate_limiter_storage

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
