framework:
    secret: '%env(APP_SECRET)%'
    session: true
    csrf_protection: true
    rate_limiter:
        post_short:
            policy: sliding_window
            limit: 2
            interval: '10 seconds'
        post_hourly:
            policy: sliding_window
            limit: 30
            interval: '1 hour'
        post:
            policy: compound
            limiters:
                - post_short
                - post_hourly
        post_duplicate:
            policy: sliding_window
            limit: 1
            interval: '3 minutes'

when@test:
    framework:
        test: true
