services:
    app:
        build:
            context: .
            target: development
        ports:
            - '8000:8000'
        environment:
            APP_ENV: dev
            APP_DEBUG: '1'
        volumes:
            - .:/app
            - vendor:/app/vendor

    vite:
        build:
            context: .
            dockerfile: Dockerfile.vite
        ports:
            - '5173:5173'
        volumes:
            - .:/app
            - node_modules:/app/node_modules

volumes:
    node_modules:
    vendor:
