services:
    app:
        build:
            context: .
        ports:
            - '8000:8000'
        environment:
            APP_ENV: dev
            APP_DEBUG: '1'
        volumes:
            - .:/app
            - vendor:/app/vendor

volumes:
    vendor:
