parameters:
    app.title: '%env(APP_TITLE)%'
    app.timezone: '%env(APP_TIMEZONE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appTimezone: '%app.timezone%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Post\PostRepository:
        factory: ['@App\Post\PostRepositoryFactory', 'create']
