parameters:
    app.title: '%env(APP_TITLE)%'
    app.timezone: '%env(APP_TIMEZONE)%'
    app.cloud_mode: '%env(bool:CLOUD_MODE)%'
    app.admin_password_hash: '%env(ADMIN_PASSWORD_HASH)%'
    app.visitor_limit: 300
    app.page_view_started_at: '2026/08/12'
    app.page_view_initial_value: 0
    app.page_view_filename: '%kernel.project_dir%/var/data/page-views.txt'
    app.site_settings_filename: '%kernel.project_dir%/var/data/site-settings.json'
    app.post_archive_directory: '%kernel.project_dir%/var/data/archive'
    app.archive_s3_prefix: '%env(ARCHIVE_S3_PREFIX)%'
    app.central_post_limit: 500
    app.post_max_author_chars: 30
    app.post_max_email_chars: 255
    app.post_max_title_chars: 40
    app.post_max_message_lines: 50
    app.post_max_line_chars: 200
    app.links_filename: '%kernel.project_dir%/config/links.md'
    app.colors:
        background: '#004040'
        text: '#ffffff'
        link: '#eeffee'
        visited_link: '#dddddd'
        active_link: '#ff0000'
        hover_link: '#10e0e0'
        subject: '#fffffe'
        quote: '#cccccc'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appTimezone: '%app.timezone%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Post/ArchivedPostRepository.php'
            - '../src/Post/DailyPostArchive.php'
            - '../src/Post/S3PostArchive.php'

    App\Post\PostRepository:
        factory: ['@App\Post\PostRepositoryFactory', 'create']

    App\Post\PostArchive:
        factory: ['@App\Post\PostArchiveFactory', 'create']

    App\PageView\PageViewCounter:
        factory: ['@App\PageView\PageViewCounterFactory', 'create']

    App\Settings\SiteSettingsRepository:
        factory: ['@App\Settings\SiteSettingsRepositoryFactory', 'create']

    App\Settings\SiteSettings:
        arguments:
            $defaultTitle: '%app.title%'
            $defaultCentralPostLimit: '%app.central_post_limit%'

    App\Settings\AdminPassword:
        arguments:
            $defaultHash: '%app.admin_password_hash%'

    App\Visitor\VisitorCounter:
        arguments:
            $filename: '%kernel.cache_dir%/visitors.json'
            $limit: '%app.visitor_limit%'
